const listData = [
    {
        name: 'Eya khlifi',
        id: '#14251',
        title: 'Bon pour mandat',
        amount: '450 DT',
        date: '10 Mai, 24',
    },
    {
        //image: 'assets/images/users/avatar-2.jpg',
        name: 'Amir khlifi',
        id: '#14252',
        title: 'Bon pour mandat',
        amount: '1000 DT',
        date: '11 Mai, 24',
    },
    {
        //image: 'assets/images/users/avatar-7.jpg',
        name: 'Assma Ben naya',
        id: '#14253',
        title: 'Bon pour mandat',
        amount: '500 DT',
        date: '11 Mai, 24',
    },
    {
        //image: 'assets/images/users/avatar-8.jpg',
        name: 'Mariem Hajjem',
        id: '#14254',
        title: 'Bon pour mandat',
        amount: '1200 DT',
        date: '11 Mai, 24',
    },
    {
        //image: 'assets/images/users/avatar-5.jpg',
        name: 'Hedi Jawedi',
        id: '#14255',
        title: 'Bon pour mandat',
        amount: '1100 DT',
        date: '12 Mai, 24',
    },
    {
        name: 'Sonia khlifi',
        id: '#14256',
        title: 'Bon pour mandat',
        amount: '1000 DT',
        date: '12 Mai, 24',
    },
    {
        //image: 'assets/images/users/avatar-1.jpg',
        name: 'Ahmed khlifi',
        id: '#14257',
        title: 'Bon pour mandat',
        amount: '1148 DT',
        date: '12 Mai, 24',
    },
    {
        name: 'Sonia khlifi',
        id: '#14258',
        title: 'Bon pour mandat',
        amount: '1259 DT',
        date: '12 Mai, 24',
    },
    {
        //image: 'assets/images/users/avatar-4.jpg',
        name: 'Akrem khlifi',
        id: '#14257',
        title: 'Bon pour acceptation du mandat',
        amount: '1350 DT',
        date: '12 Mai, 24',
    },
];

export { listData };
